name: Deploy Release

on:
  push:
    tags:
      - "*.*.*" 

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false